name: CI Check

on: [push, pull_request]

jobs:
  gitHubActionForPytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    name: GitHub Action
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Install dependencies
      run: |
        python -m pip install -r requirements-dev.txt
    - name: Lint
      run: |
        make lint-check
    - name: Unittest
      run: |
        make coverage-check
